---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse

  - src: git@github.com:MrVanG0gh/Netology_ansible_04_role_vector-role.git
    scm: git
    version: "1.0.0"
    name: vector-role

  - src: git@github.com:MrVanG0gh/Netology_ansible_04_role_lighthouse-role.git
    scm: git
    version: "1.0.0"
    name: lighthouse-role